# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.250
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20


## Mod Properties
mod_id=create_rackets
mod_name=Create Rackets Event Mod
mod_license=MIT
mod_version=1.21.1-1.0b
mod_group_id=net.Wekston.create_rackets
mod_authors=Wekston
mod_description=This mod adds an artillery danger event.