modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/create-rackets-event"
modId="create_rackets"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.create_rackets]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_rackets]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_rackets]]
modId="create"
mandatory=true
versionRange="[6.0.7,)"
ordering="NONE"
side="BOTH"
[[dependencies.create_rackets]]
modId="createbigcannons"
mandatory=true
versionRange="[5.11.1,)"
ordering="NONE"
side="BOTH"